#include <iostream>
#include "menus.h"

using namespace std;

/**
PARTE 3:

REPORTES:

INTRODUCCION:
-LISTAR LOS PASAJEROS QUE PERTENEZCAN A UN NIVEL DE CIUDADANIA QUE SE INGRESA POR TECLADO
-LISTAR LA CANTIDAD DE CAPITANES DE RANGO "VETERANO".
-LISTAR EL MES DE NACIMIENTO EN EL QUE NACIERON MAYOR DCANTIDAD DE PASAJEROS.

FACIL:
-LISTAR PARA CADA VIAJE LA CANTIDAD DE PASAJEROS QUE TUVO ESE VIAJE.

**/

int main(){

menuPrincipal();
return 0;
}
