#include <iostream>
#include "menus.h"

using namespace std;

/**
PARTE 3:

REPORTES:

INTRODUCCION:
-LISTAR LOS PASAJEROS QUE PERTENEZCAN A UN NIVEL DE CIUDADANIA QUE SE INGRESA POR TECLADO
-LISTAR LA CANTIDAD DE CAPITANES DE RANGO "VETERANO".
-LISTAR EL MES DE NACIMIENTO EN EL QUE NACIERON MAYOR DE CANTIDAD DE PASAJEROS.

FACIL:
-LISTAR PARA CADA VIAJE LA CANTIDAD DE PASAJEROS QUE TUVO ESE VIAJE.
-LISTAR LA CANTIDAD DE VIAJES DE LOS CAPITANES DE RANGO VETERANO. (MOSTRAR UNA CANTIDAD POR CADA CAPITAN)

INTERMEDIO:
-LISTAR EL MES CON MAYOR CANTIDAD DE PASAJES VENDIDOS ENTRE TODOS LOS AÑOS

-DIFICIL:
-LISTAR LOS CAPITANES QUE TENGAN VIAJES CUYO NOMBRE DEL PLANETA DE DESTINO SE INGRESA POR TECLADO.
-LISTAR EL DESTINO MAS VISITADO
-GENERAR UN NUEVO ARCHIVO CON LA SIGUIENTE INFORMACION:
-ID DEL CAPITAN
-NOMBRE DEL CAPITAN
-CANTIDAD DE VIAJES

-GENERAR UN ARCHIVO NUEVO CON LOS CAPITANES QUE HAYAN REALIZADO AL MENOS UN VIAJE A UN DESTINO CUYO NOMBBRE SE INGRESA POR TECLADO
**/

int main(){

menuPrincipal();
return 0;
}
